"""added isbn in Book models

Revision ID: 317710f6e327
Revises: c3ed3dff73a7
Create Date: 2025-01-24 14:47:29.825183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '317710f6e327'
down_revision: Union[str, None] = 'c3ed3dff73a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('isbn', sa.String(), nullable=True))
    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.drop_column('books', 'isbn')
    # ### end Alembic commands ###
